- added reusable components for button, input, menu, multi-select - added directive for click outside element event - added common utils for sort, debounce - added user name func

diff --git a/.github/workflows/github-actions-ec2.yml b/.github/workflows/github-actions-ec2.yml
--- a/.github/workflows/github-actions-ec2.yml
+++ b/.github/workflows/github-actions-ec2.yml
@@ -16,34 +16,34 @@ jobs:
         uses: actions/checkout@v2
       - name: Run unit tests
         run: sudo ./scripts_docker.sh run-unit-tests
-      - name: Zip allure reports
-        if: success() || failure()
-        run: cd src && mv allure-results results && zip -r results.zip results
-      - name: Copy zipped reports to allure server
-        if: success() || failure()
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          source: "src/results.zip"
-          target: "/home/ubuntu/allure-docker/projects/frontend-unit/"
-          strip_components: 1
-      - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
-        if: success() || failure()
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          script: >-
-            cd /home/ubuntu/allure-docker/projects/frontend-unit &&
-            sudo rm -rf results &&
-            unzip results.zip &&
-            rm results.zip &&
-            curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-unit
+      # - name: Zip allure reports
+      #   if: success() || failure()
+      #   run: cd src && mv allure-results results && zip -r results.zip results
+      # - name: Copy zipped reports to allure server
+      #   if: success() || failure()
+      #   uses: appleboy/scp-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     source: "src/results.zip"
+      #     target: "/home/ubuntu/allure-docker/projects/frontend-unit/"
+      #     strip_components: 1
+      # - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
+      #   if: success() || failure()
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     script: >-
+      #       cd /home/ubuntu/allure-docker/projects/frontend-unit &&
+      #       sudo rm -rf results &&
+      #       unzip results.zip &&
+      #       rm results.zip &&
+      #       curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-unit
   e2e-tests-cypress:
     name: Run cypress e2e tests
     runs-on: ubuntu-latest
@@ -68,34 +68,34 @@ jobs:
           MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
       - name: Run cypress e2e tests
         run: ./scripts_docker.sh run-e2e-tests-cypress
-      - name: Zip allure reports
-        if: success() || failure()
-        run: cd cypress && mv allure-results results && zip -r results.zip results
-      - name: Copy zipped reports to allure server
-        if: success() || failure()
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          source: "cypress/results.zip"
-          target: "/home/ubuntu/allure-docker/projects/frontend-e2e-cypress/"
-          strip_components: 1
-      - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
-        if: success() || failure()
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          script: >-
-            cd /home/ubuntu/allure-docker/projects/frontend-e2e-cypress &&
-            sudo rm -rf results &&
-            unzip results.zip &&
-            rm results.zip &&
-            curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e-cypress
+      # - name: Zip allure reports
+      #   if: success() || failure()
+      #   run: cd cypress && mv allure-results results && zip -r results.zip results
+      # - name: Copy zipped reports to allure server
+      #   if: success() || failure()
+      #   uses: appleboy/scp-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     source: "cypress/results.zip"
+      #     target: "/home/ubuntu/allure-docker/projects/frontend-e2e-cypress/"
+      #     strip_components: 1
+      # - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
+      #   if: success() || failure()
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     script: >-
+      #       cd /home/ubuntu/allure-docker/projects/frontend-e2e-cypress &&
+      #       sudo rm -rf results &&
+      #       unzip results.zip &&
+      #       rm results.zip &&
+      #       curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e-cypress
   e2e-tests-playwright:
     name: Run playwright e2e tests
     runs-on: ubuntu-latest
@@ -115,54 +115,56 @@ jobs:
         run: echo "password" > backend/docker_secrets/redis_pwd.txt
       - name: Run playwright e2e tests
         run: ./scripts_docker.sh run-e2e-tests-playwright
-      - name: Zip allure reports
-        if: success() || failure()
-        run: cd playwright && mv allure-results results && zip -r results.zip results
-      - name: Copy zipped reports to allure server
-        if: success() || failure()
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          source: "playwright/results.zip"
-          target: "/home/ubuntu/allure-docker/projects/frontend-e2e-playwright/"
-          strip_components: 1
-      - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
-        if: success() || failure()
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          script: >-
-            cd /home/ubuntu/allure-docker/projects/frontend-e2e-playwright &&
-            sudo rm -rf results &&
-            unzip results.zip &&
-            rm results.zip &&
-            curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e-playwright
+      # - name: Zip allure reports
+      #   if: success() || failure()
+      #   run: cd playwright && mv allure-results results && zip -r results.zip results
+      # - name: Copy zipped reports to allure server
+      #   if: success() || failure()
+      #   uses: appleboy/scp-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     source: "playwright/results.zip"
+      #     target: "/home/ubuntu/allure-docker/projects/frontend-e2e-playwright/"
+      #     strip_components: 1
+      # - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
+      #   if: success() || failure()
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     script: >-
+      #       cd /home/ubuntu/allure-docker/projects/frontend-e2e-playwright &&
+      #       sudo rm -rf results &&
+      #       unzip results.zip &&
+      #       rm results.zip &&
+      #       curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e-playwright
   deploy:
     name: Deploy to EC2
     runs-on: ubuntu-latest
     needs: [unit-tests, e2e-tests-cypress, e2e-tests-playwright]
     steps:
-      - name: Build & Restart Frontend - build new container to serve latest frontend
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          port: 22
-          script: >-
-            cd /home/ubuntu &&
-            sudo rm -rf frontend-vue-old &&
-            mv frontend-vue frontend-vue-old &&
-            git clone -b main https://github.com/mg-login-examples/login-frontend-vue-vite.git frontend-vue &&
-            cd frontend-vue &&
-            git clone -b main https://github.com/mg-login-examples/login-frontend-vue-vite.git backend &&
-            cd .. &&
-            sudo rm -rf frontend-vue-old &&
-            cd frontend-vue &&
-            ./scripts_docker.sh launch-frontend-cloud-dev
+      - name: Do Not Deploy
+        run: echo "Do Not Deploy"
+      # - name: Build & Restart Frontend - build new container to serve latest frontend
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     script: >-
+      #       cd /home/ubuntu &&
+      #       sudo rm -rf frontend-vue-old &&
+      #       mv frontend-vue frontend-vue-old &&
+      #       git clone -b main https://github.com/mg-login-examples/login-frontend-vue-vite.git frontend-vue &&
+      #       cd frontend-vue &&
+      #       git clone -b main https://github.com/mg-login-examples/login-frontend-vue-vite.git backend &&
+      #       cd .. &&
+      #       sudo rm -rf frontend-vue-old &&
+      #       cd frontend-vue &&
+      #       ./scripts_docker.sh launch-frontend-cloud-dev
